# CONFIGS
EDITOR="code"
LANG="en_US.UTF-8"
PATH=".venv/bin:$HOME/.local/bin:$HOME/.pyenv/bin:$HOME/.local/share/fnm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/snap/bin:/snap/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
# OPTIONS
ZSH_THEME="dracula-pro"
ZSH_CUSTOM=$HOME/.zsh.d
# EXPORTS
export KEYTIMEOUT=1
export ZSH=$HOME/.oh-my-zsh
export PYENV_ROOT="$HOME/.pyenv"
export PYTHONBREAKPOINT=ipdb.set_trace
export VIRTUAL_ENV_DISABLE_PROMPT=1
# PLUGINS
eval "$(pyenv init --path)"
eval "$(fnm env --use-on-cd)"
