export EDITOR="vim"
export KEYTIMEOUT=1
export LANG="en_US.UTF-8"
export PATH="$PWD/.venv/bin:$HOME/.local/bin:$HOME/.tfenv/bin/:$HOME/.antigravity/antigravity/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.zsh.d
export ZSH_THEME="starship"
