# BINDKEY
bindkey -v
# PLUGINS
plugins=(
    alias-tips
    aws
    ansible
    colored-man-pages
    command-not-found
    docker
    gcloud
    gh
    git
    npm
    pip
    python
    sudo
    terraform
    starship
    vi-mode
    vscode
    zoxide
    zsh-autopair
    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)
# ALIASES
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi
# PRIVATE
if [ -f ~/.private ]; then
    source ~/.private
fi
# SOURCES
source $ZSH/oh-my-zsh.sh
