gui:
  showIcons: false
  returnImmediately: true
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
  nerdFontsVersion: ""
