apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <project-name>
  namespace: <project-name>
spec:
  ingressClassName: traefik
  rules:
    - host: <project-name>.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <project-name>-service
                port:
                  number: 8080
