[flags]
default_time_value = "60s"
default_widget_count = 1
default_widget_type = "proc"
hide_table_gap = true
mem_as_value = true
rate = "1s"
temperature_type = "celsius"

[flags.processes]
default_grouped = false
default_tree = true
disable_advanced_kill = true
