version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /dot
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps)"
    groups:
      go-modules:
        patterns:
          - "*"
