" MAIN SETTINGS

"" compatibility
set nocompatible                " disable vi compatibility
set nomodeline                  " security best pratice

"" interface
set so=10                       " activate a margin for vertical scrolling
set title                       " activate vim title on the current xterm
set mouse=a                     " activate mouse selection for every mode
set wildmenu                    " activate a menu for autocompletion
set wildmode=list:longest       "   (menu behaviour)
set nospell                     " deactivate inline spell check
set spelllang=en                "   (default spelling language)
set background=dark             " activate editor theming
set t_Co=256                    "   (add more colors)
set t_md=                       " no bold fonts

"" display
set ruler                       " display cursor location
set number 				        " display line numbers (gutter)
set showmode			        " display the current mode
set noshowmatch			        " don't display matching parenthesis
let loaded_matchparen = 1       "   (same with nocompatible set)
set syntax=on                   " display syntaxic coloration
set laststatus=2                " display the status line (always)
set lazyredraw                  " don't display while executing macros (performance)
set splitright                  " put new vertical window on the right of the current buffer
"set splitbelow                  " put horizontal window below the current buffer
set shortmess=a                 " use abbreviations for status messages

"" completion
set completeopt-=preview        " disable the preview completion window

"" indentation
set expandtab                   " insert spaces when hitting TABs
set shiftround                  " round indent value to a multiple of 'shiftwidth'
set autoindent                  " align the new line indent with the previous line
set tabstop=4                   " a hard TAB displays as 4 spaces
set shiftwidth=4                " operation >> indents 4 spaces; << unindents 4 spaces
set softtabstop=4               " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set backspace=indent,eol,start  " allow backspacing over everything in insert mode 

"" search
set incsearch			        " show first match as the search proceeds
set nohlsearch                  " deactivate search highlighting
set ignorecase                  " case insensitivity
set smartcase                   "   (only when no upper letter is used)
set gdefault                    " replace all occurences in line by default (/g)

"" wraping
set wrap                        " wrap text when text length > window size
set linebreak                   " don't break line in a middle of a word
set textwidth=0                 " don't use hard wrapping

"" folding
set foldlevel=20                " folding level
set foldmethod=indent           " folding behaviour

"" read/write
set encoding=utf-8              " default encoding
set ffs=unix,dos,mac            " default newline

"" saving/backup
set hidden                      " buffers can exist in background
set nowb                        " no backup before overriding
set autowrite                   " write buffer on focus loss/make
set nobackup                    " no backup files
set noswapfile                  " no .swp files
set history=100                 " history size
set undolevels=100              " undo size

" PLUGINS
"" set the runtime path to include Vundle and initialize
filetype off                    " required by Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"" include plugins
Bundle 'gmarik/vundle'
Bundle 'easymotion/vim-easymotion'
Bundle 'flazz/vim-colorschemes'
Bundle 'airblade/vim-gitgutter'
Bundle 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
let g:airline_theme='simple'
Bundle 'powerline/fonts'

"" all the of your plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" HOOKS

"" automatic spell checking for the following files
autocmd BufNewFile,BufRead *.{txt,tex,md} setlocal spell spelllang=en

"" automatic text wrapping on open, read and save for the following files
autocmd BufNewFile,BufRead *.{txt,tex,md} setlocal textwidth=80 whichwrap+=h,l,<,>,[,]

"" exclusions
set suffixes=.jpg,.png,.jpeg,.gif,.bak,~,.swp,.swo,.o,.pyc
set wildignore+=*.fls,*.pdf,*.bbl,*.aux,*.dvi

" SHORTCUTS

"" change leader characters
let mapleader="\<Space>"
let maplocalleader="\\"
map ; :
vmap ; :
noremap ;; ;

"" break bad Habits
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap Q g
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"" basic actions
nnoremap <leader>z za
nnoremap <leader>R :r! 
nnoremap <leader>r :reg<CR>
nnoremap <leader>b :buffer 
nnoremap <leader>B :ls<CR>
nnoremap <leader>E :edit<CR>
nnoremap <leader>e :tabedit 
nnoremap <leader>h :set hls!<CR>
nnoremap <leader>C :setlocal spell! spelllang=en,fr<CR>
nnoremap <leader>g gqip
nnoremap <leader>G gggqG
nnoremap <leader>? :help 
nnoremap <leader>O :set ro<CR>

"" hex editor
nnoremap <leader>#x :%!xxd<CR>
nnoremap <leader>#t :%!xxd -r<CR>

"" copy and paste
nnoremap Y y$
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

"" move around windows
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h
nnoremap H gT
nnoremap L gt
nnoremap <leader>V :vsplit 
nnoremap <leader>H :hsplit 
nnoremap <leader>L :vnew<CR><c-w>h

"" plugins
nnoremap <leader>- :make<CR>
nnoremap <leader>+i :PluginInstall<CR>
nnoremap <leader>+u :PluginUpdate<CR>
nnoremap <leader>+c :PluginClean<CR>
nnoremap <leader>+v :tabedit $MYVIMRC<CR>
nnoremap <leader>+l :source $MYVIMRC<CR>
nnoremap <leader>` :NERDTreeToggle<CR>

"" theme
if filereadable("~/.vim/bundle/vim-colorschemes")
    colorscheme molokai
endif
