" vim: fdm=marker
" STARTING{{{
if !exists(" $VIMDIR" )
    let $VIMDIR=$HOME.'/.vim/'
endif
" }}}
" CHECKING{{{
set nocompatible
" }}}
" SETTING{{{
"" FILES{{{
set path+=**
set report=0
set autochdir
" }}}
"" RULER{{{
set ruler
set number
set relativenumber
" }}}
"" STATUS{{{
set showcmd
set showmode
set wildmenu
set laststatus=2
set completeopt=longest,menuone
set wildignore+=*.pdf,*.bbl,*.aux,*.pyc
set statusline=%t\ %c,%l/%L\ %P\%=%r%y\ [%{&ff}]\ [%{strlen(&fenc)?&fenc:'none'}]\ %m
" }}}
"" WINDOW{{{
set title
set mouse=a
set t_Co=256
set cursorline
set splitright
set splitbelow
set synmaxcol=1000
set background=dark
" }}}
"" EDITING{{{
set hidden
set nospell
set confirm
set autoread
set autowrite
set autowriteall
set history=1000
set encoding=utf-8
set spelllang=en,fr
set ffs=unix,dos,mac
set clipboard=unnamedplus
set suffixes=.swp,.jpg,.png,.jpeg,.gif,.pyc,.pyo
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" }}}
"" FOLDING{{{
set foldlevel=0
set foldmethod=marker
set foldlevelstart=99
" }}}
"" SPELLING{{{
set spell
set spelllang=en,fr
" }}}
"" WRAPPING{{{
set wrap
set linebreak
set textwidth=0
" }}}
"" NAVIGATION{{{
set mat=1
set gdefault
set wrapscan
set hlsearch
set incsearch
set showmatch
set smartcase
set ignorecase
set nojoinspaces
set nostartofline
set scrolloff=10
set sidescrolloff=5
" }}}
"" INDENTATION{{{
set smarttab
set expandtab
set autoindent
set copyindent
set shiftround
set tabstop=4 
set shiftwidth=4
set softtabstop=4
set backspace=indent,eol,start
" }}}
"" NOTIFICATION{{{
set noerrorbells
set novisualbell
" }}}
"" OPTIMIZATION{{{
set ttyfast
set lazyredraw
set shell=/bin/bash
" }}}
"" CONSERVATION{{{
set backup
set undofile
set backupext=-vimbackup
set undodir=$VIMDIR/undo/
set directory=$VIMDIR/swap/
set backupdir=$VIMDIR/backup/
set viminfo ='200,n$VIMDIR/viminfo
" }}}
" }}}
" BINDING{{{
"" LEADERS{{{
map ; :
vmap ; :
noremap ;; ;
let mapleader=" " 
let maplocalleader="," 
" }}}
"" ACTIONS{{{
nnoremap <leader>\ :set 
nnoremap <leader><Tab> <c-^>
nnoremap <leader>>  :shell<CR>
nnoremap <leader># :set spell!<CR>
nnoremap <leader>' :edit $MYVIMRC<CR>
nnoremap <leader>@ :edit ~/.vimrc.py<CR>
nnoremap <leader>" :source $MYVIMRC<CR>
nnoremap <leader>! :w !sudo tee > /dev/null %<CR>
nnoremap <leader>.m :setlocal foldmethod=marker<CR>
nnoremap <leader>.s :setlocal foldmethod=syntax<CR>
nnoremap <leader>.i :setlocal foldmethod=indent<CR>
nnoremap <leader>.p :setlocal filetype=python<CR>
nnoremap <leader>.t :setlocal filetype=text<CR>
" }}}
"" DEFAULT{{{
noremap j gj
noremap k gk
noremap B g^
noremap E g$
noremap Y y$
noremap U <C-r>
noremap J <C-d>
noremap K <C-u>
nnoremap <CR> <C-e>
xnoremap < <gv
xnoremap > >gv
nnoremap Z :x<CR>
nnoremap Q :w<CR>:bd<CR>
nnoremap = gqap
nnoremap + gg=G
nnoremap zj o<Esc>k
nnoremap zk O<Esc>j
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
noremap gs :sort<CR>
noremap gj :join<CR>
noremap L :bnext<CR>
noremap H :bprevious<CR>
nnoremap <silent> <ESC> :nohl<CR>
nnoremap <expr> n  'Nn'[v:searchforward]
nnoremap <expr> N  'nN'[v:searchforward]
" }}}
" }}}
" PLUGINS{{{
syntax enable
filetype plugin on
filetype indent on
if !empty(glob($VIMDIR.'/autoload/plug.vim'))
call plug#begin($VIMDIR.'/plugged')
"" fzf{{{
Plug 'junegunn/fzf',{'dir': '~/.fzf', 'do': './install --bin'}
Plug 'junegunn/fzf.vim'
nnoremap <leader>/ :Ag<CR>
nnoremap <leader>A :Tags<CR>
nnoremap <leader>a :BTags<CR>
nnoremap <leader>m :Marks<CR>
nnoremap <leader>L :Lines<CR>
nnoremap <leader>C :Colors<CR>
nnoremap <leader>l :BLines<CR>
nnoremap <leader>F :GFiles<CR>
nnoremap <leader>f :Files .<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>B :Filetypes<CR>
nnoremap <leader>y :BCommits<CR>
nnoremap <leader>Y :Commits<CR>
nnoremap <leader>w :Windows<CR>
nnoremap <leader>i :Snippets<CR>
nnoremap <leader>h :History<CR>
nnoremap <leader>: :History:<CR>
nnoremap <leader>; :History/<CR>
nnoremap <leader>? :Helptags<CR>
nnoremap <leader><Space> :Commands<CR>
let $FZF_DEFAULT_COMMAND = 'ag --hidden -p ~/.agignore -g "" '
" }}}
"" ycm{{{
Plug 'Valloric/YouCompleteMe', {'dir': '~/.vim/plugged/YouCompleteMe', 'do': './install.py --clang-completer'}
nnoremap <leader>j :YcmCompleter GoTo<CR>
nnoremap <leader>d :YcmCompleter GetDoc<CR>
nnoremap <leader>v :YcmCompleter GoToReferences<CR>
let g:ycm_key_list_select_completion = ['<C-n>']
let g:ycm_key_list_previous_completion = ['<C-p>']
" }}}
"" codi{{{
Plug 'metakirby5/codi.vim'
nnoremap <leader>c :Codi!!<CR>
" }}}
"" plug{{{
nnoremap <leader>pd :PlugDiff<CR>
nnoremap <leader>pc :PlugClean<CR>
nnoremap <leader>ps :PlugStatus<CR>
nnoremap <leader>pu :PlugUpdate<CR>
nnoremap <leader>pg :PlugUpgrade<CR>
nnoremap <leader>pi :PlugInstall<CR>
" }}}
"" test{{{
Plug 'janko-m/vim-test'
let test#strategy = "vimux" 
let g:test#preserve_screen = 1
nnoremap <leader>tf :TestFile<CR>
nnoremap <leader>tl :TestLast<CR>
nnoremap <leader>ts :TestSuite<CR>
nnoremap <leader>tv :TestVisit<CR>
nnoremap <leader>tt :TestNearest<CR>
" }}}
"" sneak{{{
Plug 'justinmk/vim-sneak'
let g:sneak#label = 1
let g:sneak#s_next = 1
let g:sneak#use_ic_scs = 1
" }}}
"" emmet {{{
Plug 'mattn/emmet-vim'
" }}}
"" snake{{{
Plug 'amoffat/snake'
if filereadable(expand($VIMDIR.'/bundle/snake/plugin/snake.vim'))
    source $VIMDIR/bundle/snake/plugin/snake.vim
endif
nnoremap <leader>$ :edit ~/.vimrc.py<CR>
" }}}
"" vimux{{{
Plug 'benmills/vimux'
nnoremap <leader>r :VimuxPromptCommand<CR>
nnoremap <leader>R :VimuxRunLastCommand<CR>
" }}}
"" eunuch {{{
Plug 'tpope/vim-eunuch'
nnoremap <leader>ox :Chmod 
nnoremap <leader>oc :Mkdir 
nnoremap <leader>oo :Rename 
nnoremap <leader>oD :Delete<CR>
" }}}
"" pencil{{{
Plug 'reedes/vim-pencil'
let g:pencil#textwidth = 100
let g:pencil#wrapModeDefault = 'soft'
nnoremap <leader>W :SoftPencil<CR>
" }}}
"" tagbar{{{
Plug 'majutsushi/tagbar'
let g:tagbar_autofocus = 1
nnoremap <leader>n :TagbarToggle<CR>
" }}}
"" vimtex{{{
Plug 'lervag/vimtex',{ 'for': 'tex' }
" }}}
"" airline{{{
Plug 'bling/vim-airline' 
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
" }}}
"" molokai{{{
Plug 'tomasr/molokai'
let g:molokai_original = 1
" }}}
"" tabular{{{
Plug 'godlygeek/tabular'
noremap <leader>X :Tabularize 
noremap <leader>x, :Tabularize /,<CR>
noremap <leader>x, :Tabularize /;<CR>
" }}}
"" fugitive{{{
Plug 'tpope/vim-fugitive'
noremap <leader>G Git 
noremap <leader>gj :Glcd 
noremap <leader>gh :Gpush<CR>
noremap <leader>gl :Gpull<CR>
noremap <leader>gm :Gmove
noremap <leader>gw :Gwrite<CR>
noremap <leader>gc :Gcommit<CR>
noremap <leader>gs :Gstatus<CR>
noremap <leader>go :Gbrowse<CR>
noremap <leader>gb :Gblame<CR>
noremap <leader>gd :Gvdiff<CR>
noremap <leader>gr :Gremove<CR>
" }}}
"" nerdtree{{{
Plug 'scrooloose/nerdtree' 
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
let g:NERDTreeQuitOnOpen = 1
let NERDTreeIgnore=['\.pyc$', '__pycache__', '\~$']
nnoremap <leader>~ :NERDTreeFind<CR>
nnoremap <leader>` :NERDTreeToggle<CR>
" }}}
"" startify{{{
Plug 'mhinz/vim-startify'
let g:startify_session_dir = $VIMDIR.'/session/'
nnoremap <leader>S :Startify<CR>
nnoremap <leader>sl :SLoad<CR>
nnoremap <leader>ss :SSave<CR>
nnoremap <leader>sc :SClose<CR>
nnoremap <leader>sd :SDelete<CR>
" }}}
"" gitgutter{{{
Plug 'airblade/vim-gitgutter'
let g:gitgutter_grep = 'ag'
let g:gitgutter_map_keys = 0
nnoremap ]g <Plug>GitGutterNextHunk
nnoremap [g <Plug>GitGutterPrevHunk
" }}}
"" syntastic{{{
Plug 'vim-syntastic/syntastic'
nnoremap <leader>e :Errors<CR>
nnoremap <leader>E :SyntasticToggleMode<CR>
let g:syntastic_check_on_wq = 0
let g:syntastic_check_on_open = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
" }}}
"" thesaurus{{{
Plug 'beloglazov/vim-online-thesaurus'
let g:online_thesaurus_map_keys = 0
nnoremap <leader>U :Thesaurus 
nnoremap <leader>u :OnlineThesaurusCurrentWord<CR>
" }}}
"" ultisnips{{{
Plug 'SirVer/ultisnips'
nnoremap <leader>I :UltiSnipsEdit<CR>
let g:UltiSnipsEditSplit = 'context'
let g:UltiSnipsExpandTrigger=" <tab>" 
let g:UltiSnipsListSnippets=" <s-tab>" 
let g:UltiSnipsJumpForwardTrigger=" <c-n>" 
let g:UltiSnipsJumpBackwardTrigger=" <c-p>" 
let g:UltiSnipsSnippetsDir = $VIMDIR.'/snippets/'
" }}}
"" autoformat {{{
Plug 'Chiel92/vim-autoformat'
nnoremap <leader>= :Autoformat<CR>
let g:formatdef_black = '"black --quiet -"'
let g:formatdef_isort = '"isort --quiet -"'
let g:formatdef_isort_black = '"isort --quiet - | black --quiet -"'
" }}}
"" easy-align{{{
Plug 'junegunn/vim-easy-align'
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
" }}}
"" vim-polyglot{{{
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['latex']
" }}}
"" projectionist{{{
Plug 'tpope/vim-projectionist'
nnoremap <leader>k :A<CR>
" }}}
"" tmux-navigator{{{
Plug 'christoomey/vim-tmux-navigator'
let g:tmux_navigator_save_on_switch = 1
" }}}
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-abolish'
Plug 'lepture/vim-jinja'
Plug 'wellle/targets.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-commentary'
Plug 'Raimondi/delimitMate'
Plug 'vim-scripts/matchit.zip'
Plug 'farmergreg/vim-lastplace'
Plug 'christoomey/vim-sort-motion'
Plug 'terryma/vim-multiple-cursors'
Plug 'michaeljsmith/vim-indent-object'
Plug 'coderifous/textobj-word-column.vim'
Plug 'aklt/plantuml-syntax',{'for': 'plantuml'}
Plug 'scrooloose/vim-slumlord',{'for': 'plantuml'}
call plug#end()
endif
try
    colorscheme molokai
catch
    colorscheme darkblue
endtry
"" }}}
" PROLANG{{{
"" python{{{
let test#python#runner = 'pytest'
let g:formatters_python = ['isort_black', 'black', 'isort']
let g:syntastic_python_checkers = ['mypy', 'pyflakes']
autocmd Filetype python setlocal foldmethod=indent
autocmd BufWrite *.py :Autoformat
" }}}
" }}}
