set nocompatible                " disable vi compatibility
filetype off                    " no file type detection
set nomodeline                  " security advice

" INTERFACE
set so=10                       " activate a margin on vertical scrolling
set title                       " activate vim title on the current xterm
set mouse=a                     " activate mouse selection for every mode
set wildmenu                    " activate a menu for autocompletion
set wildmode=list:longest       "   (menu behaviour)
set nospell                     " activate inline spell check
set spelllang=en                "   (spelling language)
colorscheme darkblue            " activate colorscheme

" DISPLAY
set ruler                       " display cursor location
set syntax=on                   " display syntaxic coloration
set number 				        " display line numbers (gutter)
set showmode			        " display the current mode
set showmatch			        " display matching parenthesis
set laststatus=2                " display the status line (always)

" INDENTATION
set expandtab                   " insert spaces when hitting TABs
set shiftround                  " round indent to multiple of 'shiftwidth'
set autoindent                  " align the new line indent with the previous line
set textwidth=79                " lines longer than 79 columns will be broken
set tabstop=4                   " a hard TAB displays as 4 columns
set shiftwidth=4                " operation >> indents 4 columns; << unindents 4 columns
set softtabstop=4               " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set backspace=indent,eol,start  " allow backspacing over everything in insert mode 

" SEARCH
set incsearch			        " show match as the search proceeds
set hlsearch                    " search highlighting
set ignorecase                  " case insensitivity
set smartcase                   "   (only when no caps is used)

" FOLDING
set foldlevel=20                " folding level
set foldmethod=indent           " folding behaviour

" READ/WRITE
set nowrap                      " don't wrap text
set encoding=utf-8              " default encoding
set ffs=unix,dos,mac            " default newline

" SAVING/BACKUP
set hidden                      " buffers can exist in background
set nowb                        " no backup before overriding
set nobackup                    " no backup files
set noswapfile                  " no .swp files
set history=100                 " history size
set undolevels=100              " undo size

" EXCLUSION
set suffixes=.jpg,.png,.jpeg,.gif,.bak,~,.swp,.swo,.o,.pyc

" PLUGINS
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle Manage Vundle
Bundle 'gmarik/vundle'

Bundle 'scrooloose/nerdtree'
Bundle 'ivanov/vim-ipython'
source $HOME/.vim/bundle/vim-ipython/ftplugin/python/ipy.vim
let g:ipy_perform_mappings = 0
nmap  <buffer> <silent> <C-p>       :python run_this_line()<CR>
vmap  <buffer> <silent> <C-P>       :python run_these_lines()<CR>
nmap  <buffer> <silent> <S-p>       :python run_this_file()<CR>
"map  <buffer> <silent> <LocalLeader>d <Plug>(IPython-OpenPyDoc)
"map  <buffer> <silent> <LocalLeader>s <Plug>(IPython-UpdateShell)
"map  <buffer> <silent> <S-F9>         <Plug>(IPython-ToggleReselect)
"map  <buffer>          <C-F5>         <Plug>(IPython-ToggleSendOnSave)

" all the of your plugins must be added before the following line
call vundle#end()
filetype plugin on
filetype indent on

" SHORTCUTS
let mapleader="\<Space>"        " set map leader (user extension shortcut)_
" Basic
nnoremap <leader>w :w<CR>
nnoremap <leader>x :x<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>h :nohl<CR>
nnoremap <leader>t :tabedit 
nnoremap <leader>T :tabedit $MYVIMRC<CR>
nnoremap <leader>L :source $MYVIMRC<CR>
nnoremap <leader>V :vsplit 
nnoremap <leader>H :hsplit 
nnoremap <leader>? :help 
" Copy & Paste
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
" Plugins
nnoremap <leader>B :PluginInstall<CR>
nnoremap <leader>U :PluginUpdate<CR>
nnoremap <leader>` :NERDTreeToggle<CR>
