[settings]
github_attestations = false
lockfile = true
slsa = false

[tools]
"aqua:abiosoft/colima" = "latest"
"aqua:docker/cli" = "latest"
"aqua:docker/compose" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"aqua:git-lfs/git-lfs" = "latest"
"aqua:gitleaks/gitleaks" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:terrastruct/d2" = "latest"
"aqua:turbot/steampipe" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@google/jules" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:lighthouse" = "latest"
"npm:neovim" = "latest"
"pipx:ptpython" = "latest"
"pipx:pynvim" = "latest"
ast-grep = "latest"
atuin = "latest"
bat = "latest"
bottom = "latest"
chezmoi = "latest"
delta = "latest"
doggo = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
pre-commit = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
terraform = "latest"
tree-sitter = "latest"
uv = "latest"
xh = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
