[settings]
github_attestations = false
lockfile = true
slsa = false

[tools]
"aqua:fish-shell/fish-shell" = "latest"
"npm:@angular/cli" = "latest"
"npm:@google/clasp" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:lighthouse" = "latest"
"npm:neovim" = "latest"
"pipx:ptpython" = "latest"
"pipx:pynvim" = "latest"
age = "latest"
ast-grep = "latest"
atuin = "latest"
bat = "latest"
bottom = "latest"
carapace = "latest"
chezmoi = "latest"
d2 = "latest"
delta = "latest"
doggo = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
firebase = "latest"
fzf = "latest"
gcloud = "latest"
gemini-cli = "latest"
gh = "latest"
git-lfs = "latest"
gitleaks = "latest"
hadolint = "latest"
jq = "latest"
jules = "latest"
just = "latest"
k9s = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
pipx = "latest"
pre-commit = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
steampipe = "latest"
terraform = "latest"
tree-sitter = "0.26.8"
uv = "latest"
xh = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
