git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showIcons: false
  showFileTree: true
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#94e2d5'
    cherryPickedCommitFgColor:
      - '#cba6f7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
os:
  editPreset: nvim
