[mgr]
linemode = "size"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true

[opener]
edit = [{ run = 'nvim "$@"', block = true, desc = "nvim" }]

[open]
prepend_rules = [{ mime = "text/*", use = "edit" }]
