-- ASCII for all icon-using plugins
return {
	{
		"LazyVim/LazyVim",
		opts = {
			icons = {
				misc = { dots = "..." },
				ft = { octo = "", gh = "", ["markdown.gh"] = "" },
				dap = {
					Stopped = { "=> ", "DiagnosticWarn", "DapStoppedLine" },
					Breakpoint = "* ",
					BreakpointCondition = "? ",
					BreakpointRejected = { "! ", "DiagnosticError" },
					LogPoint = ".>",
				},
				diagnostics = { Error = "E ", Warn = "W ", Hint = "H ", Info = "I " },
				git = { added = "+ ", modified = "~ ", removed = "- " },
				kinds = {
					Array = "[] ",
					Boolean = "b ",
					Class = "C ",
					Codeium = "AI ",
					Color = "# ",
					Control = "ctl ",
					Collapsed = ">",
					Constant = "c ",
					Constructor = "Co ",
					Copilot = "AI ",
					Enum = "E ",
					EnumMember = "em ",
					Event = "ev ",
					Field = "f ",
					File = "F ",
					Folder = "D ",
					Function = "fn ",
					Interface = "I ",
					Key = "k ",
					Keyword = "kw ",
					Method = "m ",
					Module = "M ",
					Namespace = "ns ",
					Null = "0 ",
					Number = "n ",
					Object = "o ",
					Operator = "op ",
					Package = "pkg ",
					Property = "p ",
					Reference = "r ",
					Snippet = "s ",
					String = "str ",
					Struct = "S ",
					Supermaven = "AI ",
					TabNine = "AI ",
					Text = "t ",
					TypeParameter = "T ",
					Unit = "u ",
					Value = "v ",
					Variable = "var ",
				},
			},
		},
	},

	{ "nvim-mini/mini.icons", opts = { style = "ascii" } },

	{
		"nvim-lualine/lualine.nvim",
		opts = { options = { icons_enabled = false } },
	},

	{
		"nvim-neo-tree/neo-tree.nvim",
		opts = {
			default_component_configs = {
				icon = {
					folder_empty = "[-]",
					folder_empty_open = "[-]",
					folder_closed = "[+]",
					folder_open = "[-]",
					default = "[ ]",
				},
				name = {
					use_git_status_colors = true,
				},
			},
		},
	},
	{
		"folke/snacks.nvim",
		opts = {
			picker = {
				icons = {
					files = {
						enabled = false,
						dir = "[+] ",
						dir_open = "[-] ",
						file = "[ ] ",
					},
					keymaps = { nowait = "! " },
					tree = {
						vertical = "| ",
						middle = "|-",
						last = "`-",
					},
					undo = { saved = "* " },
					ui = {
						live = "> ",
						hidden = "h",
						ignored = "i",
						follow = "f",
						selected = "[x] ",
						unselected = "[ ] ",
					},
					git = {
						enabled = false,
						commit = "* ",
						staged = "S",
						added = "A",
						deleted = "D",
						ignored = "I",
						modified = "M",
						renamed = "R",
						unmerged = "U",
						untracked = "?",
					},
					diagnostics = { Error = "E ", Warn = "W ", Hint = "H ", Info = "I " },
					lsp = {
						unavailable = "x ",
						enabled = "+ ",
						disabled = "- ",
						attached = "* ",
					},
					kinds = {
						Array = "[] ",
						Boolean = "b ",
						Class = "C ",
						Color = "# ",
						Control = "ctl ",
						Collapsed = "> ",
						Constant = "c ",
						Constructor = "Co ",
						Copilot = "AI ",
						Enum = "E ",
						EnumMember = "em ",
						Event = "ev ",
						Field = "f ",
						File = "F ",
						Folder = "D ",
						Function = "fn ",
						Interface = "I ",
						Key = "k ",
						Keyword = "kw ",
						Method = "m ",
						Module = "M ",
						Namespace = "ns ",
						Null = "0 ",
						Number = "n ",
						Object = "o ",
						Operator = "op ",
						Package = "pkg ",
						Property = "p ",
						Reference = "r ",
						Snippet = "s ",
						String = "str ",
						Struct = "S ",
						Text = "t ",
						TypeParameter = "T ",
						Unit = "u ",
						Unknown = "? ",
						Value = "v ",
						Variable = "var ",
					},
				},
			},
			indent = {
				indent = { char = "|" },
				scope = { char = "|" },
			},
		},
	},
	{
		"MeanderingProgrammer/render-markdown.nvim",
		opts = {
			bullet = {
				icons = { "*", "+", "-", ">" },
				ordered_icons = {},
			},
			checkbox = {
				unchecked = { icon = "[ ]" },
				checked = { icon = "[x]" },
				custom = {},
			},
			code = { sign = false },
			dash = { icon = "-" },
			pipe_table = { preset = "none" },
			link = {
				image = "",
				email = "",
				hyperlink = "",
				wiki = { icon = "" },
				custom = {},
			},
			sign = { enabled = false },
			quote = { icon = "|" },
		},
	},
}
