# yaml-language-server: $schema=https://gh-dash.dev/schema.json

defaults:
  refetchIntervalMinutes: 10
  prApproveComment: ""
pager:
  diff: delta
repoPaths:
  "*/*": "~/*/*"
prSections:
  - title: Needs Review
    filters: "is:open review-requested:@me"
  - title: CI Red
    filters: "is:open author:@me status:failure"
  - title: Changes Requested
    filters: "is:open author:@me review:changes_requested"
  - title: Ready to Merge
    filters: "is:open author:@me review:approved status:success"
  - title: Involved
    filters: "is:open involves:@me -author:@me"
  - title: Drafts
    filters: "is:open author:@me draft:true"
issuesSections:
  - title: Assigned
    filters: "is:open assignee:@me"
  - title: Needs Human
    filters: "is:open label:needs-human"
  - title: Untriaged
    filters: "is:open -label:priority/p0 -label:priority/p1 -label:priority/p2"
  - title: In Progress
    filters: "is:open label:status/in-progress"
  - title: Involved
    filters: "is:open involves:@me"
keybindings:
  prs:
    - key: E
      name: review in octo
      command: >-
        nvim "+Octo https://github.com/{{.RepoName}}/pull/{{.PrNumber}}"
    - key: D
      name: full diff
      command: >-
        gh pr diff --repo {{.RepoName}} {{.PrNumber}} | delta --paging=always
    - key: O
      name: lazygit
      command: >-
        test -n "{{.RepoPath}}" && cd {{.RepoPath}} && lazygit
  issues:
    - key: E
      name: open in octo
      command: >-
        nvim "+Octo https://github.com/{{.RepoName}}/issues/{{.IssueNumber}}"
theme:
  colors:
    primary: "#82aaff"
    secondary: "#c099ff"
    faint: "#636da6"
    warning: "#ffc777"
    error: "#ff757f"
    success: "#c3e88d"
