" INIT
set nocompatible
set shortmess=I
set noswapfile
set nobackup
" FILE
set hidden
set path+=**
set linebreak
" SHELL
set shell=/bin/bash
set clipboard=unnamedplus
" WILD
set wildmenu
set wildmode=list:longest,full
set completeopt=menuone,preview
" INDENT
set smarttab
set expandtab
set autoindent
set shiftround
set backspace=indent,eol,start
" SEARCH
set incsearch
" WINDOW
set scrolloff=10
set laststatus=2
set relativenumber
set statusline=\ %n:\ \%f\ %y%=%r\ %l\ :\ %c\ (%p%%)\ 
" COLORS
syntax enable
colorscheme zellner
" PLUGINS
filetype indent on
filetype plugin on
let g:loaded_netrw = 1
let g:loaded_matchparen = 0
let g:loaded_netrwPlugin = 1
" KEYMAPS
nnoremap <space> :
vnoremap <space> :
nnoremap g. :edit $MYVIMRC<CR>
" AUTOCMD
augroup vim
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup end
