### ZSH environment ###

export PYENV_ROOT="$HOME/.pyenv"

export PATH="$HOME/bin:$HOME/.local/bin:$PYENV_ROOT/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

### Private environment ###

if [ -f ~/.privenv ]; then
    . ~/.privenv
fi
