### ZSH Configuration ###

# Installation path
export RPS1="%{$reset_color%}" # spaceship theme
export ZSH=~/.oh-my-zsh

# Set name of the theme
ZSH_THEME="spaceship"
export SPACESHIP_EXIT_CODE_SHOW=true

# Set the custom folder
ZSH_CUSTOM=$HOME/.zsh.d

# Set the execution time
HIST_STAMPS="yyyy-mm-dd"

# Set the ZSH plugins to load
plugins=(catimg
         celery
         command-not-found
         docker
         encode64
         httpie
         jsontools
         lein
         pyenv
         pylint
         python
         stack
         sudo
         systemd
         urltools
         vi-mode
         wd
         web-search
         zsh-autosuggestions
         zsh-syntax-highlighting
         )

# Set umask
umask 0077

# Make awesome
source $ZSH/oh-my-zsh.sh

# Switch to vi
bindkey -v
export KEYTIMEOUT=1
bindkey '^o' clear-screen

# Enable byobu
if [ -x "$(command -v byobu)" ]; then
    _byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
fi

# Enable pyenv
if [ -d "$PYENV_ROOT" ]; then
    eval "$(pyenv init -)"
fi

# Enable autoenv
if [ -x "$(command -v activate.sh)" ]; then
    source "$(which activate.sh)"
fi

# Set caps lock
if [ -n "$DISPLAY" ]; then
    setxkbmap -option caps:escape
fi

# Set preferred editor
export EDITOR='vim'

# Set preferred language
export LANG=en_US.UTF-8

# Add support for 256 colors
export TERM=screen-256color

### Alias Configuration ###

alias -g Z='| pigz'
alias -g F='| head'
alias -g T='| tail'
alias -g L='| less'
alias -g G='| grep'
alias -g W='| wc -l'
alias -g U='| unpigz -c'
alias -g V='| $EDITOR -'
alias -g J='| js-beautify'
alias -g C='| xsel --clipboard'
alias -g X='| xmllint --format -'
alias -g H='--help'
alias -g NE='2>/dev/null'
alias -g NUL='>/dev/null2>&1'

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
