### ZSH Configuration ###

# Installation path
export ZSH=~/.oh-my-zsh

# Set name of the theme
ZSH_THEME="fmind"

# Set the custom folder
ZSH_CUSTOM=$HOME/.zsh.d

# Set the execution time
HIST_STAMPS="yyyy-mm-dd"

# Set the ZSH plugins to load
plugins=(catimg
         command-not-found
         docker
         encode64
         httpie
         jsontools
         lein
         python
         stack
         sudo
         systemd
         urltools
         vi-mode
         wd
         web-search)

## INCLUDES

# Make ZSH awesome again !
source $ZSH/oh-my-zsh.sh

# Switch to vi
bindkey -v
export KEYTIMEOUT=1
bindkey '^o' clear-screen

# Enable byobu
_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true

# Enable autoenv
if [ -x "$(command -v activate.sh)" ]; then
    source "$(which activate.sh)"
fi

# Set umask
umask 0077

# Set caps lock to escape
if [ -n "$DISPLAY" ]; then
    setxkbmap -option caps:escape
fi

# setopt MENU_COMPLETE

# Add support for 256 colors
export TERM=screen-256color

# Set preferred editor for local and remote sessions
export EDITOR='vim'

# Set preferred language for local and remote sessions
export LANG=en_US.UTF-8

### Alias Configuration ###

# Alias: GLOBAL
alias -g Z='| pigz'
alias -g F='| head'
alias -g T='| tail'
alias -g L='| less'
alias -g G='| grep'
alias -g W='| wc -l'
alias -g V='| $EDITOR -'
alias -g J='| js-beautify'
alias -g X='| xsel --clipboard'
alias -g H='--help'
alias -g NE='2>/dev/null'
alias -g NUL='>/dev/null2>&1'

# Alias: NAVIGATION
c() { cd "$1"; ls;}
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias l="ls"
alias ll="ls -lFh"
alias la="ls -lAFh"
alias lr="ls -lRFh"
alias lt="ls -ltFh"
alias lh="ls -ld .*"
alias back="cd $OLDPWD"

# Alias: EDITION
alias a="cat"
alias z="pigz"
alias uz="unpigz -c"
alias cl="clear"
alias ve="emacs -nw"
alias vee="emacs &"
alias ved="emacs --daemon"
alias vet="emacsclient --tty"
alias veg="emacsclient --create-frame . &"
alias v="$EDITOR"
alias vi="$EDITOR"
alias vim="$EDITOR"
alias vig="$EDITOR -g"
alias vir="$EDITOR -R"
alias vip="$EDITOR -p"
alias vis="sudo $EDITOR"
alias virc='$EDITOR ~/.vimrc'

# Alias: INTEGRATION
alias x="exit"
alias o="xdg-open"
alias f='dolphin . &'
alias dark="xbacklight -set 10"
alias bright="xbacklight -set 100"
alias pbcopy="xsel --clipboard --output"
alias pbclear="xsel --clipboard --clear"

# Alias: INFORMATION
alias h="history"
alias gg="google"
alias release="lsb_release -c"
alias cmount="mount | column -t"
alias extip='curl icanhazip.com'

# Alias: DISTRIBUTION
alias search="apt-cache search"
alias clean="sudo apt-get clean"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias install="sudo apt-get install"
alias autoclean="sudo apt-get autoclean"
alias remove="sudo apt-get remove --purge"
alias megaup="update && upgrade && autoremove"
alias dist-upgrade="sudo apt-get dist-upgrade"
alias autoremove="sudo apt-get autoremove --purge"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias: CONFIGURATION
alias zshsrc='source ~/.zshrc'
alias zshsenv='source ~/.zshenv'
alias zshrc='$EDITOR ~/.zshrc && zshsrc'
alias zshenv='$EDITOR ~/.zshenv && zshsenv'
alias privsenv='source ~/.privenv'
alias privenv='$EDITOR ~/.privenv && privsenv'
alias warprc='$EDITOR ~/.warprc'
alias pypirc='$EDITOR ~/.pypirc'
alias sshrc='$EDITOR ~/.ssh/config'
alias idearc='$EDITOR ~/.ideavimrc'
alias emacsrc='$EDITOR ~/.spacemacs'
alias latexmkrc='$EDITOR ~/.latexmkrc'
alias cookierc='$EDITOR ~/.cookiecutterrc'

# Alias: ADMINISTRATION
alias chx="chmod u+x "
alias kila='killall -9'
alias tunnel='ssh -nNT'
alias sysctl='systemctl'
alias srv='sudo service'
alias rsinc="rsync -avzu"
alias psmem='ps aux | sort -nk 4'
alias psproc='ps aux | sort -nk 3'
backup() { cp "$1"{,.bak}; }

# Alias: FILTERING
alias jqr="jq -r"
alias t="head -n1"
alias h1="head -n1"
alias h5="head -n5"
alias h10="head -n10"
alias h15="head -n15"
alias t1="tail -n1"
alias t5="tail -n5"
alias t10="tail -n10"
alias t15="tail -n15"
alias igrep="grep -i"
alias colt="column -t"
alias sortp='sort --parallel=$(nproc --all)'

# Alias: LANGUAGES
## Java
alias ja="java"
alias jac="javac"
alias jaj="java -jar"
# ## Groovy
# alias gro="groovy"
# alias gron="groovy -n"
# alias grop="groovy -p"
# alias gros="groovysh"
# alias grod="groovydoc"
## Clojure
alias cljs="planck"
alias leinr="lein repl"
alias leina="lein ancient"
alias leinfig="lein figwheel"
alias leincss="lein garden auto"
leinp() { lein with-profile "$1" repl } 
alias leinap="lein ancient check-profiles"
alias leinrc="$EDITOR ~/.lein/profiles.clj"
alias bootrc="$EDITOR ~/.boot/boot.properties"
## (should) improve boot startup time
export BOOT_JVM_OPTIONS="-client 
-XX:+TieredCompilation 
-XX:TieredStopAtLevel=1 
-Xmx2g 
-XX:+UseConcMarkSweepGC 
-XX:+CMSClassUnloadingEnabled 
-Xverify:none"
# ## Elixir
# alias er="iex"
# alias ep="iex -S mix"
# alias em="mix"
# alias e="elixir"
# alias ec="elixirc"
## Haskell
# alias hh="stack"
# alias ho="hoogle"
# alias hn="stack new"
# alias he="stack exec"
# alias hr="stack repl"
# alias hg="stack ghci"
# alias ht="stack test"
# alias hb="stack build"
# alias hn="stack bench"
# alias hs="stack setup"
# alias hu="stack update"
# alias hz="stack upgrade"
# alias hd="stack haddock"
# alias hi="stack install"
# alias hv="stack --version"
# alias hw="stack test --file-watch"
# alias hp="stack repl --test --bench"
# alias hj="stack ghci --ghci-options -XOverloadedStrings"
# alias hrc="$EDITOR ~/.stack/config.yaml"
## Python
alias pp="pip"
alias p="python"
alias pt="pytest"
alias ph="pydoc"
alias p2="python2"
alias p3="python3"
alias pdt="python -m doctest"
alias put="python -m unittest"
alias toxe="tox -e"
alias pu="python setup.py"
alias ppl="pip list --user"
alias pps="pip search --user"
alias ppi="pip install --user"
alias ppu="pip uninstall"
alias ppf="pip freeze --user > requirements.txt"
alias ppr="pip install --user -r requirements.txt"
alias pi="ipython --profile=fmind"
alias pk="ipython kernel --profile=fmind"
alias pn="jupyter-notebook --profile=fmind --NotebookApp.token="
alias pnp"ipcluster start -n $(nproc)"
alias pva="source venv/bin/activate"
alias pvd="deactivate"
pvi() { virtualenv "venv" "$@" && echo 'source "$(dirname $0)/venv/bin/activate"' > .env }
pvc() { mkdir "$1" && cd "$1" && pyvi }
pvg() { pyvc "$1" && pyva }

# Alias: PROGRAMMING
## Git
alias g="git"
alias gm="git submodule"
alias gn="$EDITOR .gitignore"
alias grc="$EDITOR ~/.gitconfig"
mygh() { git clone git@github.com:fmind/$1.git }
## Project
alias m="make"
## Template
alias ck="cookiecutter"
## Ansible
alias anpl="ansible-playbook"
alias anpls="ansible-playbook --ask-become"
alias anpl-user="ansible-playbook *user.yml"
alias anpl-sys="ansible-playbook --ask-become *sys.yml"
## Docker
alias dk="docker"
alias dkrmf="docker rm --force"
alias dkrmo="docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm"
alias dk-spark='docker run --name pyspark -p 9000:8888 -v  "$(pwd)":/home/jovyan/work jupyter/pyspark-notebook'
alias dk-scipy="docker run --name pyscipy -p 9000:8888 -v "$(pwd)":/home/jovyan/work jupyter/scipy-notebook"
alias dk-fxmongo='docker run --name pymongo -p 9000:8888 -v "$(pwd)":/home/jovyan/work --link mongo:mongo freaxmind/nosql'
alias dk-mongo='docker run --name mongo -v "$(pwd)/data/db":/data/db mongo --smallfiles'
alias dk-zoo='docker run --name zookeeper --restart always zookeeper'

# Alias: SHARING
alias httpserve="python3 -m http.server"

# Alias: EDITING
alias texmake="latexmk -pv"
alias texview="latexmk -pv"
alias texlive="latexmk -pvc"
alias texclean="latexmk -c"
alias texpurge="latexmk -C"
alias imgwhite="convert -flatten "
alias slides="git clone git@github.com:fmind/my-slides"
