---
- name: package
  community.general.npm:
    name: "@google/gemini-cli"
    state: latest
    global: true
  tags: user

- name: folder
  ansible.builtin.file:
    path: "~/.gemini/"
    state: directory
    mode: "0755"
  tags: user

- name: settings
  ansible.builtin.file:
    src: "{{ role_path }}/files/settings.json"
    dest: ~/.gemini/settings.json
    state: link
    force: true
  tags: user

- name: instructions
  ansible.builtin.file:
    src: "{{ role_path }}/files/GEMINI.md"
    dest: ~/.gemini/GEMINI.md
    state: link
    force: true
  tags: user

- name: components
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/.gemini/{{ item }}
    state: link
    force: true
  loop:
    - agents
    - commands
    - skills
  tags: user
