" CHECKUP {{{
set nomodeline
set nocompatible
"}}}
" STARTUP {{{
let $VIMDIR=$HOME.'/.vim/'
"}}}
" SET-UP {{{
""" WINDOW {{{
set title
set mouse=a
set splitright
set splitbelow
set t_Co=256
set conceallevel=2
set background=dark
" set colorcolumn=100
let g:loaded_matchparen=1
"}}}
""" SIDEBAR {{{
set ruler
set number
set relativenumber
"}}}
""" STATUSBAR {{{
set showcmd
set showmode
set wildmenu
set shortmess=c
set laststatus=2
set wildmode=longest:full,full
set wildignore+=*.pdf,*.bbl,*.aux,*.pyc
"}}}
""" FOLDING {{{
set foldlevel=20
set foldmethod=marker
set foldlevelstart=10
"}}}
""" WRAPPING {{{
set wrap
set linebreak
set textwidth=0
"}}}
""" EDITION {{{
set hidden
set confirm
set autoread
set autowrite
set autowriteall
set encoding=utf-8
set ffs=unix,dos,mac
set clipboard=unnamedplus
set suffixes=.swp,.jpg,.png,.jpeg,.gif,.pyc,.pyo
"}}}
""" NAVIGATION {{{
set gdefault
set hlsearch
set incsearch
set smartcase
set ignorecase
set noshowmatch
set nojoinspaces
set nostartofline
set scrolloff=10
set sidescrolloff=5
"}}}
""" IDENTATION {{{
set expandtab
set autoindent
set copyindent
set shiftround
set tabstop=4 
set shiftwidth=4
set softtabstop=4
set backspace=indent,eol,start
"}}}
""" NOTIFICATION {{{
set noerrorbells
set novisualbell
"}}}
""" OPTIMIZATION {{{
set ttyfast
set lazyredraw
"}}}
""" CONSERVATION {{{
set backup
set undofile
set updatecount=100
set undodir=$VIMDIR/undo/
set directory=$VIMDIR/swap/
set backupdir=$VIMDIR/backup/
set viminfo ='200,n$VIMDIR/viminfo
"}}}
"}}}
" PLUGUP {{{
syntax enable
filetype plugin on
filetype indent on

if !empty(glob($HOME.'/.vim/autoload/plug.vim'))
call plug#begin($HOME.'/.vim/plugged')
""" TUNING {{{
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-repeat'
Plug 'alvan/vim-closetag'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/matchit.zip'
Plug 'junegunn/vim-easy-align'
Plug 'easymotion/vim-easymotion'
let g:EasyMotion_smartcase = 1
Plug 'christoomey/vim-sort-motion'
Plug 'christoomey/vim-tmux-navigator'
let g:tmux_navigator_save_on_switch = 1
Plug 'michaeljsmith/vim-indent-object'
"}}}
""" THEMING {{{
Plug 'tomasr/molokai'
Plug 'bling/vim-airline' 
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
"}}}
""" WRITING {{{
Plug 'godlygeek/tabular'
" Plug 'vim-pandoc/vim-pandoc'
" Plug 'vim-pandoc-syntax/vim-pandoc'
Plug 'plasticboy/vim-markdown'
Plug 'beloglazov/vim-online-thesaurus'
"}}}
""" PROGRAMMING {{{
Plug 'mattn/emmet-vim'
let g:user_emmet_leader_key='<leader>h'
Plug 'fisadev/vim-isort'
Plug 'sheerun/vim-polyglot'
"}}}
""" VERSIONNING {{{
Plug 'airblade/vim-gitgutter'
"}}}
""" DEVELOPPING {{{
" Plug 'janko-m/vim-test'
" let g:test#preserve_screen = 1
" let test#python#runner = 'pytest'
Plug 'w0rp/ale'
Plug 'SirVer/ultisnips'
let g:UltiSnipsEditSplit = 'context'
let g:UltiSnipsSnippetsDir = $HOME.'/.vim/snippets/'
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --bin'}
Plug 'junegunn/fzf.vim'
Plug 'majutsushi/tagbar'
Plug 'mhinz/vim-startify'
Plug 'scrooloose/nerdtree' 
let NERDTreeIgnore=['\.pyc$', '\~$']
Plug 'jistr/vim-nerdtree-tabs'
Plug 'Chiel92/vim-autoformat'
let g:formatters_python = ['yapf']
Plug 'Valloric/YouCompleteMe', {'dir': $HOME.'/.vim/plugged/YouCompleteMe/', 'do': './install.py'}
let g:ycm_goto_buffer_command = 'new-or-existing-tab'
let g:ycm_autoclose_preview_window_after_completion= 1
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
"}}}
call plug#end()
colorscheme molokai
endif
"}}}
" HOOKS {{{
""" restore last cursor position
autocmd! BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

""" disable auto-comment for all file
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

""" change fold method for Python files
autocmd! BufNewFile,BufRead *.py setlocal foldmethod=indent

"""  automatically save buffers on focus lost
autocmd! FocusLost * silent! wa

""" automatically add spelling and wrapping for textual files
autocmd! BufNewFile,BufRead *.{txt,tex,rst,md} setlocal spell spelllang=en textwidth=100 whichwrap+=h,l,<,>,[,]
"}}}
" KEYBINDINGS {{{
""" BETTER LEADER {{{
map ; :
vmap ; :
noremap ;; ;
let mapleader="\<Space>"
let maplocalleader=","
 "}}}
""" BETTER HABITS {{{
nnoremap <Up> <NOP>
inoremap <Up> <NOP>
nnoremap <Down> <NOP>
inoremap <Down> <NOP>
nnoremap <Left> <NOP>
inoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Right> <NOP>
":inoremap <Esc> <NOP>
"}}}
""" BETTER DEFAULTS {{{
map Y y$
map U <C-r>
nnoremap j gj
vnoremap j gj
nnoremap k gk
vnoremap k gk
nnoremap 0 g0
vnoremap 0 g0
nnoremap $ g$
vnoremap $ g$
nnoremap ^ g^
vnoremap ^ g^
nnoremap _ g_
vnoremap _ g_
nnoremap / /\v
vnoremap / /\v
xnoremap <  <gv
xnoremap >  >gv
inoremap jk  <Esc>
inoremap kj  <Esc>
nnoremap Q :x<CR>
nnoremap zj o<Esc>k
nnoremap zk O<Esc>j
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
nnoremap <silent> <ESC> :nohl<CR>
nnoremap <expr> n  'Nn'[v:searchforward]
nnoremap <expr> N  'nN'[v:searchforward]
 "}}}
""" BASIC ACTIONS {{{
nnoremap <leader>? :help 
nnoremap <leader>j :join<CR>
vnoremap <leader>j :join<CR>
vnoremap <leader>s :sort<CR>
nnoremap <leader>m :make<CR>
"}}}
""" INTERNAL ACTIONS {{{
nnoremap <leader>MR :source $MYVIMRC<CR>
nnoremap <silent> <leader>MB :buffers<CR>
nnoremap <silent> <leader>MM :message<CR>
nnoremap <silent> <leader>MP :register<CR>
nnoremap <silent> <leader>ME :tabedit $MYVIMRC<CR>
"}}}
""" ADVANCED ACTIONS {{{
"""""" execute shell command
nnoremap <leader>! :!
nnoremap <leader>1 :r!
"""""" format current buffer
nnoremap <leader>+ gggqG
"""""" format current paragrah
nnoremap <leader>= gqip
""""""" highlight last inserted text
nnoremap <leader>v `[v`]
""""""" switch between the last two files
nnoremap <leader>k <c-^>
""""""" get answer from the internet
nnoremap <leader>D :!howdoi 
"""""" write a file as sudo
nnoremap <leader>W :w !sudo tee > /dev/null %<CR>
"""""" add spelling for en/fr
nnoremap <silent> <leader>S :setlocal spell! spelllang=en,fr<CR>
"""""" edit the current macro
nnoremap <leader>@  :<c-u><c-r><c-r>='let @'. v:register .' = '. string(getreg(v:register))<cr><c-f><left>
"}}}
""" TAB MANAGEMENT {{{
nnoremap <leader>e :tabedit 
nnoremap <silent> K :tabnext<CR>
nnoremap <silent> J :tabprevious<CR>
"}}}
""" FOLD MANAGEMENT {{{
nnoremap <leader>z za
nnoremap <leader>Z zM
"}}}
""" BUFFER MANAGEMENT {{{
nnoremap <silent> H <C-e>
nnoremap <silent> L <C-y>
nnoremap <leader>E :edit 
nnoremap <silent> <leader><Tab> :bnext<cr>
nnoremap <silent> <leader><S-Tab> :bprevious<cr>
"}}}
""" WINDOWS MANAGEMENT {{{
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <silent> <leader>x :x<CR>
nnoremap <silent> <leader>H :split<CR>
nnoremap <silent> <leader>V :vsplit<CR>
"}}}
""" PLUGINS MANAGEMENT {{{
nnoremap <silent> <leader>PI :PlugInstall<CR>
nnoremap <silent> <leader>PG :PlugUpgrade<CR>
nnoremap <silent> <leader>PU :PlugUpdate<CR>
nnoremap <silent> <leader>PS :PlugStatus<CR>
nnoremap <silent> <leader>PC :PlugClean<CR>
nnoremap <silent> <leader>PL :PlugList<CR>
nnoremap <silent> <leader>PD :PlugDocs<CR>
nnoremap <leader>PR :source $MYVIMRC<CR>
"}}}
""" PLUGINS CONFIGURATIONS {{{
"""""" edition {{{
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
nnoremap <silent> <leader>A :Tabularize
nnoremap <silent> <leader>a= :Tabularize /=
vnoremap <silent> <leader>a= :Tabularize /=
nnoremap <silent> <leader>a/ :Tabularize /|
vnoremap <silent> <leader>a/ :Tabularize /|
nnoremap <silent> <leader>q :Autoformat<CR>
"}}}
"""""" navigation {{{
nmap s <Plug>(easymotion-s2)
nnoremap <silent> <leader>/ :Ag<CR>
nnoremap <silent> <leader>T :Tags<CR>
nnoremap <silent> <leader>t :BTags<CR>
nnoremap <silent> <leader>' :Marks<CR>
nnoremap <silent> <leader>L :Lines<CR>
nnoremap <silent> <leader>l :BLines<CR>
nnoremap <silent> <leader>F :GFiles<CR>
nnoremap <silent> <leader>f :Files .<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>y :History<CR>
nnoremap <silent> <leader>w :Windows<CR>
nnoremap <silent> <leader>i :Snippets<CR>
nnoremap <silent> <leader><Space> :Commands<CR>
nnoremap <silent> <leader>d :YcmCompleter GetDoc<CR>
nnoremap <silent> <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
"}}}
"""""" definition {{{
nnoremap <leader>U :Thesaurus 
nnoremap <leader>u :OnlineThesaurusCurrentWord<CR>
"}}}
"""""" testing {{{
" nnoremap <silent> <localleader>f :TestFile<CR>
" nnoremap <silent> <localleader>l :TestLast<CR>
" nnoremap <silent> <localleader>s :TestSuite<CR>
" nnoremap <silent> <localleader>g :TestVisit<CR>
" nnoremap <silent> <localleader>t :TestNearest<CR>
"}}}
"""""" toggling {{{
nnoremap <silent> <leader>; :TagbarToggle<CR>
nnoremap <silent> <leader>` :NERDTreeTabsToggle<CR>
"}}}
"""""" error management {{{
nnoremap <silent> <leader>C :ALEToggle<CR>
nnoremap <silent> <leader>c :ALENextWrap<CR>
"}}}
"""""" pandoc management {{{
" nnoremap <silent> <leader>DD :Pandoc
" nnoremap <silent> <leader>DP :autocmd! BufWrite <buffer> :Pandoc pdf<CR> 
" nnoremap <silent> <leader>DH :autocmd! BufWrite <buffer> :Pandoc html5<CR> 
"}}}
"""""" session management {{{
nnoremap <silent> <leader>NL :SLoad<CR>
nnoremap <silent> <leader>NS :SSave<CR>
nnoremap <silent> <leader>NC :SClose<CR>
nnoremap <silent> <leader>ND :SDelete<CR>
"}}}
"""""" snippet management {{{
nnoremap <silent> <leader>I :UltiSnipsEdit<CR>
"}}}
"""""" python language {{{
autocmd FileType python nnoremap <silent> <LocalLeader>i :Isort<CR>
"}}}
"}}}
