" vim: fdm=marker
" STARTING {{{
if !exists("$VIMDIR")
    let $VIMDIR=$HOME.'/.vim/'
endif
" }}}
" CHECKING {{{
set nocompatible
" }}}
" SETTING {{{
"" FILES {{{
set path+=**
set report=0
set autochdir
let g:netrw_liststyle=3
let g:netrw_browse_split=4
let g:netrw_list_hide=netrw_gitignore#Hide()
" }}}
"" RULER {{{
set ruler
set number
set relativenumber
" }}}
"" STATUS {{{
set showcmd
set showmode
set wildmenu
set shortmess=c
set laststatus=2
set wildignore+=*.pdf,*.bbl,*.aux,*.pyc
set statusline=%t\ %c,%l/%L\ %P\%=%r%y\ [%{&ff}]\ [%{strlen(&fenc)?&fenc:'none'}]\ %m
" }}}
"" WINDOW {{{
set title
set mouse=a
set t_Co=256
set splitright
set splitbelow
set cursorline
set synmaxcol=1000
set background=dark
colorscheme darkblue
" }}}
"" EDITING {{{
set hidden
set confirm
set autoread
set autowrite
set autowriteall
set history=1000
set encoding=utf-8
set spelllang=en,fr
set ffs=unix,dos,mac
set formatoptions-=cro
set clipboard=unnamedplus
set suffixes=.swp,.jpg,.png,.jpeg,.gif,.pyc,.pyo
" }}}
"" FOLDING {{{
set foldlevel=0
set foldmethod=syntax
set foldlevelstart=99
" }}}
"" WRAPPING {{{
set wrap
set linebreak
set textwidth=0
" }}}
"" NAVIGATION {{{
set mat=1
set gdefault
set wrapscan
set hlsearch
set incsearch
set showmatch
set smartcase
set ignorecase
set nojoinspaces
set nostartofline
set scrolloff=10
set sidescrolloff=5
" }}}
"" IDENTATION {{{
set smarttab
set expandtab
set autoindent
set copyindent
set shiftround
set tabstop=4 
set shiftwidth=4
set softtabstop=4
set backspace=indent,eol,start
" }}}
"" NOTIFICATION {{{
set noerrorbells
set novisualbell
" }}}
"" OPTIMIZATION {{{
set ttyfast
set lazyredraw
set shell=/bin/bash
" }}}
"" CONSERVATION {{{
set backup
set undofile
set backupext=-vimbackup
set undodir=$VIMDIR/undo/
set directory=$VIMDIR/swap/
set backupdir=$VIMDIR/backup/
set viminfo ='200,n$VIMDIR/viminfo
" }}}
" }}}
" PLUGING {{{
syntax enable
filetype plugin on
filetype indent on
if !empty(glob($VIMDIR.'/autoload/plug.vim'))
call plug#begin($VIMDIR.'/plugged')
Plug 'tomasr/molokai'
Plug 'christoomey/vim-tmux-navigator'
let g:tmux_navigator_save_on_switch = 1
call plug#end()
colorscheme molokai
endif
"" }}}
" HOOKING {{{
""  save buffers on focus lost
autocmd! FocusLost * silent! wa
"" restore last cursor position
autocmd! BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
" }}}
" BINDING {{{
"" LEADERS {{{
map ; :
vmap ; :
noremap ;; ;
let maplocalleader=","
let mapleader="\<Space>"
noremap <leader><leader> :
" }}}
"" ACTIONS {{{
nnoremap <leader>\ :set 
nnoremap <leader><Tab> <c-^>
nnoremap <leader>' :edit $MYVIMRC<CR>
nnoremap <leader>" :source $MYVIMRC<CR>
nnoremap <leader>! :w !sudo tee > /dev/null %<CR>
" }}}
"" DEFAULT {{{
noremap j gj
noremap k gk
noremap B g^
noremap E g$
noremap Y y$
noremap gj gJ
noremap U <C-r>
noremap J <C-d>
noremap K <C-u>
xnoremap <  <gv
xnoremap >  >gv
nnoremap zj o<Esc>k
nnoremap zk O<Esc>j
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
noremap L :bnext<CR>
noremap H :bprevious<CR>
nnoremap <silent> <ESC> :nohl<CR>
nnoremap <expr> n  'Nn'[v:searchforward]
nnoremap <expr> N  'nN'[v:searchforward]
" }}}
" }}}
