#!/bin/bash

set -e

cat > README.rst <<EOF
dotfiles
========

Configuration of my favorite tools, shells and editors:

EOF

find . -maxdepth 1 -type d -not -path '*/\.*' | sort | sed -E 's?^./??' >> README.rst

printf "\n" >> README.rst
echo 'Happy Hacking !' >> README.rst

echo '[hook] README.rst was generated'

git add README.rst
