# PDF only
$pdf_mode = 1;
$dvi_mode = 0;
$postscript_mode = 0;

# Preview PDF with viewer
$pdf_previewer = "xdg-open";

# Halt auto-compilation on error
$pdflatex="pdflatex -interaction=nonstopmode -halt-on-error %O %S"
