# vim: foldmethod=marker
# SECURITY {{{
# set stricter umask
umask 0077
# don't run interactively
[ -z "$PS1" ] && return
# don't run in external editor
if [ -z "$EMACS" ] && [ -z "$MYVIMRC" ]; then
    _byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
fi
# }}}
# SETTINGS {{{
if [ -n "$DISPLAY" ]; then
    # change repeat key
    xset r rate 200 50
    # remap caps lock key
    setxkbmap -option caps:ctrl_modifier -option shift:both_capslock
fi
# }}}
# OPTIONS {{{
# match all files or 0 or more directories
shopt -s globstar
# append to the history file, no overwrite
shopt -s histappend
# check the window size after each command
shopt -s checkwinsize
# }}}
# ALIASES {{{
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi
# }}}
