### ZSH Configuration ###

# Path to oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="freaxmind"

# Uncomment the following line to change the command execution time
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$ZSH/custom/

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(vi-mode, command-not-found)

# set PATH
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PYTHONPATH="$HOME/lib:$PYTHONPATH"

## INCLUDES

# Proxy settings
[ -f ~/ENABLE_PROXY ] && {
    export HTTP_PROXY=`cat ~/ENABLE_PROXY`
    export http_proxy=$HTTP_PROXY
    export HTTPS_PROXY=$HTTP_PROXY
    export https_proxy=$HTTP_PROXY
    export FTP_PROXY=$HTTP_PROXY
    export ftp_proxy=$HTTP_PROXY
    export no_proxy=localhost
    export NO_PROXY=localhost
}

# Google settings
if [ -f ~/.googlerc ]; then
    source ~/.googlerc
fi

### User configuration ###

# Make ZSH Awesome !
source $ZSH/oh-my-zsh.sh

# Load Byoby on startup
_byobu_sourced=1 . /usr/bin/byobu-launch

# Preferred language for local and remote sessions
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'
bindkey -v

# remap caps lock key
setxkbmap -option caps:escape

# set umask
umask 0077

### Alias Configuration ###

# Alias: GLOBAL
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L='| less'
alias -g X='| xclip -selection c'
alias -g P=':$PATH'

# Alias: BASICS
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias back="cd $OLDPWD"
alias vi="vim"
alias vir="vim -R"
alias vis="sudo vim"
alias chx="chmod u+x "
backup() { cp "$1"{,.bak};}
alias cmount="mount | column -t"
alias ipinfo="curl ifconfig.me && curl ifconfig.me/host"

# Alias: QUICK ACCESS
alias c="cd"
alias v="vim"
alias x="exit"
alias l="clear"
alias o="xdg-open"
alias f='nautilus . &'
alias extip='curl icanhazip.com'
alias serve='python -m SimpleHTTPServer'
alias zshrc='$EDITOR ~/.zshrc'
alias zshsrc='source ~/.zshrc'
cls() { cd "$1"; ls;}

# Alias: PROGRAMMING
alias py2="python2"
alias py3="python3"
alias pyp="pip3"
alias pyd="ipdb"
alias pyh="pydoc"
alias pys="ipython --profile=freaxmind"
alias pyn="jupyter-notebook  --profile=freaxmind"
alias pyk="ipython kernel --profile=freaxmind"
alias pyv="source venv/bin/activate"
alias pyv-create="virtualenv --distribute --no-site-packages venv"
alias anpl="ansible-playbook"
alias cookie="cookiecutter"
alias dk="docker"

# Alias: DATA ANALYSIS
alias pjs="python3 -m json.tool"
alias pysparkn='docker run -p 8888:8888 -v "$(pwd)":/home/jovyan/work jupyter/pyspark-notebook'
alias pyscipyn="docker run -p 8888:8888 -v $(pwd):/home/jovyan/work jupyter/scipy-notebook"

# Alias: IMAGE
alias imgwhite="convert -flatten "

# Alias: DISTRIBUTION (Ubuntu)
alias search="apt-cache search"
alias install="sudo apt-get install"
alias remove="sudo apt-get remove --purge"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias clean="sudo apt-get clean"
alias autoclean="sudo apt-get autoclean"
alias autoremove="sudo apt-get autoremove --purge"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

