### ZSH Configuration ###

# Path to oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="fmind"

# Uncomment the following line to change the command execution time
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh.d

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(catimg command-not-found docker encode64 httpie gitfast jsontools lein lol python sudo urltools web-search wd)

## INCLUDES

# set PATH
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# set PROXY
[ -f ~/ENABLE_PROXY ] && {
    export HTTP_PROXY=`cat ~/ENABLE_PROXY`
    export http_proxy=$HTTP_PROXY
    export HTTPS_PROXY=$HTTP_PROXY
    export https_proxy=$HTTP_PROXY
    export FTP_PROXY=$HTTP_PROXY
    export ftp_proxy=$HTTP_PROXY
    export no_proxy=localhost
    export NO_PROXY=localhost
}

### User configuration ###

# Make ZSH Awesome !
source $ZSH/oh-my-zsh.sh

# Enable Byobu
_byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true

# Add support for 256 colors
export TERM=screen-256color

# Preferred language for local and remote sessions
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# remap caps lock backspace
setxkbmap -option caps:escape

# import private environment
if [ -f ~/.privaterc ]; then
    . ~/.privaterc
fi

# set umask
umask 0077

### Alias Configuration ###

# Alias: GLOBAL
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L='| less'
alias -g X='| xclip'
alias -g V='| vim -'
alias -g J='| js-beautify'
alias -g P=':$PATH'
alias -g NE='2>/dev/null'
alias -g NUL='>/dev/null2>&1'

# Alias: NAVIGATION
c() { cd "$1"; ls;}
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias l="ls"
alias ll="ls -lFh"
alias la="ls -lAFh"
alias lr="ls -lRFh"
alias lt="ls -ltFh"
alias lh="ls -ld .*"
alias back="cd $OLDPWD"

# Alias: EDITION
alias p="cat"
alias v="vim"
alias vi="vim"
alias vip="vim -p"
alias vir="vim -R"
alias vis="sudo vim"
alias vimrc='vi ~/.vimrc'
alias e="emacs -nw"
alias ee="emacs . &"
alias es="sudo emacs -nw"
alias eb="emacs --debug-init"
alias er="emacs -nw --eval '(setq buffer-read-only t)'"

# Alias: INTEGRATION
alias x="exit"
alias o="xdg-open"
alias f='nautilus . &'
alias dark="xbacklight -set 10"
alias bright="xbacklight -set 100"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# Alias: INFORMATION
alias h="history"
alias cmount="mount | column -t"
alias extip='curl icanhazip.com'

# Alias: DISTRIBUTION
alias search="apt-cache search"
alias install="sudo apt-get install"
alias remove="sudo apt-get remove --purge"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias megaup="update && upgrade"
alias clean="sudo apt-get clean"
alias autoclean="sudo apt-get autoclean"
alias autoremove="sudo apt-get autoremove --purge"
alias dist-upgrade="sudo apt-get dist-upgrade"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias: CONFIGURATION
alias zshsrc='source ~/.zshrc'
alias zshrc='$EDITOR ~/.zshrc && zshsrc'
alias privatesrc='source ~/.privaterc'
alias privaterc='$EDITOR ~/.privaterc && privatesrc'
alias emacsrc='$EDITOR ~/.spacemacs'
alias sshrc='$EDITOR ~/.ssh/config'
alias sshpub='cat ~/.ssh/id_rsa.pub'

# Alias: ADMINISTRATION
alias chx="chmod u+x "
alias kila='killall -9'
alias sysctl='systemctl'
alias srv='sudo service'
alias psmem='ps aux | sort -nk 4'
alias psproc='ps aux | sort -nk 3'
backup() { cp "$1"{,.bak}; }

# Alias: FILTERING
alias igrep="grep -i"
alias t="head -n1"
alias h1="head -n1"
alias h2="head -n2"
alias h3="head -n3"
alias h4="head -n4"
alias h5="head -n5"
alias t1="tail -n1"
alias t2="tail -n2"
alias t3="tail -n3"
alias t4="tail -n4"
alias t5="tail -n5"
alias jqr="jq -r"
alias colt="column -t"
alias sortp='sort --parallel=$(nproc --all)'

# Alias: PROGRAMMING
## Java
alias jajar="java -jar"
## Python
alias py2="python2"
alias py3="python3"
alias pyp="pip3"
alias pypu="pip3 install --user"
alias pyd="ipdb"
alias pyh="pydoc"
alias pys="ipython --profile=fmind"
alias pyn="jupyter-notebook  --profile=fmind"
alias pyk="ipython kernel --profile=fmind"
alias pyc="ipcluster start -n 8"
alias pyv="source venv/bin/activate"
alias pyv-create="virtualenv --distribute --no-site-packages venv"
## Clojure
alias cljrc="$EDITOR ~/.lein/profiles.clj"
alias clja="lein ancient"
alias cljap="lein ancient check-profiles"
alias clje="lein exec"
alias cljr="lein repl"
cljrp() { lein with-profile "$1" repl } 
## Ansible
alias anpl="ansible-playbook"
alias anpls="sudo ansible-playbook"
alias anpluser="ansible-playbook *user.yml"
alias anplsys="sudo ansible-playbook *sys.yml"
## Docker
alias dk="docker"
alias dkrmf="docker rm --force"
alias dkrmo="docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm"
alias pysparkn='docker run --name pyspark -p 9000:8888 -v  "$(pwd)":/home/jovyan/work jupyter/pyspark-notebook'
alias pyscipyn="docker run --name pyscipy -p 9000:8888 -v "$(pwd)":/home/jovyan/work jupyter/scipy-notebook"
alias pysparkn='docker run --name pyspark -p 9000:8888 -v "$(pwd)":/home/jovyan/work jupyter/pyspark-notebook'
alias pyscipyn="docker run --name pyscipy -p 9000:8888 -v "$(pwd)":/home/jovyan/work jupyter/scipy-notebook"
alias pymongon='docker run --name pymongo -p 9000:8888 -v "$(pwd)":/home/jovyan/work --link mongo:mongo freaxmind/nosql'
alias mongoimg='docker run --name mongo -v "$(pwd)/data/db":/data/db mongo --smallfiles'
## Make
alias m="make"
# Git
alias g="git"
alias gm="git submodule"
mygithub() { git clone git@github.com:fmind/$1.git }
alias grc="$EDITOR ~/.gitconfig"

# Alias: SHARING
alias httpserve="python3 -m http.server"

# Alias: EDITING
alias texmake="latexmk -pv"
alias texview="latexmk -pv"
alias texlive="latexmk -pvc"
alias texclean="latexmk -c"
alias texpurge="latexmk -C"
alias imgwhite="convert -flatten "
alias slides="git clone git@github.com:fmind/my-slides"
