### ZSH Configuration ###

# Installation path
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="fmind"

# Uncomment the following line to change the command execution time
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh.d

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(catimg
         command-not-found
         dircycle
         docker
         encode64
         fabric
         gitfast
         httpie
         jsontools
         lein
         lol
         python
         sudo
         systemd
         urltools
         wd
         web-search)

## INCLUDES

# Make ZSH Awesome !
source $ZSH/oh-my-zsh.sh

# enable autoenv
if [ -x "$(command -v activate.sh)" ]; then
    source "$(which activate.sh)"
fi

if [ -z "$VIMRUNTIME" ]; then
    _byobu_sourced=1 . /usr/bin/byobu-launch 2>/dev/null || true
fi

# remap caps lock backspace
setxkbmap -option caps:escape

# Add support for 256 colors
export TERM=screen-256color

# Preferred language for local and remote sessions
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# pip completion
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip

# set umask
umask 0077

### Alias Configuration ###

# Alias: GLOBAL
alias -g H='--help'
alias -g F='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L='| less'
alias -g X='| xsel --clipboard'
alias -g V='| $EDITOR -'
alias -g J='| js-beautify'
alias -g P=':$PATH'
alias -g NE='2>/dev/null'
alias -g NUL='>/dev/null2>&1'

# Alias: NAVIGATION
c() { cd "$1"; ls;}
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias l="ls"
alias ll="ls -lFh"
alias la="ls -lAFh"
alias lr="ls -lRFh"
alias lt="ls -ltFh"
alias lh="ls -ld .*"
alias back="cd $OLDPWD"

# Alias: EDITION
alias a="cat"
alias v="$EDITOR"
alias vi="$EDITOR"
alias vim="$EDITOR"
alias vig="$EDITOR -g"
alias vir="$EDITOR -R"
alias vip="$EDITOR -p"
alias vis="sudo $EDITOR"
alias virc='$EDITOR ~/.vimrc'
alias e="emacs . &"

# Alias: INTEGRATION
alias x="exit"
alias o="xdg-open"
alias f='nautilus . &'
alias dark="xbacklight -set 10"
alias bright="xbacklight -set 100"
alias pbcopy="xsel --clipboard --output"
alias pbclear="xsel --clipboard --clear"

# Alias: INFORMATION
alias h="history"
alias gg="google"
alias cmount="mount | column -t"
alias extip='curl icanhazip.com'

# Alias: DISTRIBUTION
alias search="apt-cache search"
alias install="sudo apt-get install"
alias remove="sudo apt-get remove --purge"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias megaup="update && upgrade && autoremove"
alias clean="sudo apt-get clean"
alias autoclean="sudo apt-get autoclean"
alias autoremove="sudo apt-get autoremove --purge"
alias dist-upgrade="sudo apt-get dist-upgrade"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias: CONFIGURATION
alias zshsrc='source ~/.zshrc'
alias zshsenv='source ~/.zshenv'
alias zshrc='$EDITOR ~/.zshrc && zshsrc'
alias zshenv='$EDITOR ~/.zshenv && zshsenv'
alias privsenv='source ~/.privenv'
alias privenv='$EDITOR ~/.privenv && privsenv'
alias emacsrc='$EDITOR ~/.spacemacs'
alias sshrc='$EDITOR ~/.ssh/config'
alias sshpub='cat ~/.ssh/id_rsa.pub'
alias cookierc='$EDITOR ~/.cookiecutterrc'
alias latexmkrc='$EDITOR ~/.latexmkrc'
alias pypirc='$EDITOR ~/.pypirc'
alias warprc='$EDITOR ~/.warprc'

# Alias: ADMINISTRATION
alias chx="chmod u+x "
alias kila='killall -9'
alias sysctl='systemctl'
alias srv='sudo service'
alias psmem='ps aux | sort -nk 4'
alias psproc='ps aux | sort -nk 3'
backup() { cp "$1"{,.bak}; }

# Alias: FILTERING
alias igrep="grep -i"
alias t="head -n1"
alias h1="head -n1"
alias h5="head -n5"
alias h10="head -n10"
alias h15="head -n15"
alias t1="tail -n1"
alias t5="tail -n5"
alias t10="tail -n10"
alias t15="tail -n15"
alias jqr="jq -r"
alias colt="column -t"
alias sortp='sort --parallel=$(nproc --all)'

# Alias: PROGRAMMING
## Java
alias jajar="java -jar"
## Clojure
alias leinrc="$EDITOR ~/.lein/profiles.clj"
alias leina="lein ancient"
alias leinap="lein ancient check-profiles"
alias clje="lein exec"
alias cljr="lein repl"
alias cljs="planck"
cljp() { lein with-profile "$1" repl } 
## Python
alias p="python"
alias ph="pydoc"
alias p2="python2"
alias p3="python3"
alias toxe="tox -e"
alias pt="python setup.py"
alias pp="pip"
alias ppl="pip list --user"
alias pps="pip search --user"
alias ppi="pip install --user"
alias ppu="pip uninstall --user"
alias ppf="pip freeze --user > requirements.txt"
alias ppr="pip install --user -r requirements.txt"
alias pi="ipython --profile=fmind"
alias pk="ipython kernel --profile=fmind"
alias pn="jupyter-notebook --profile=fmind --NotebookApp.token="
alias pc"ipcluster start -n $(nproc)"
alias pva="source venv/bin/activate"
alias pvd="deactivate"
pvi() { virtualenv "venv" "$@" && echo 'source "$(dirname $0)/venv/bin/activate"' > .env }
pvc() { mkdir "$1" && cd "$1" && pyvi }
pvg() { pyvc "$1" && pyva }
## Ansible
alias anpl="ansible-playbook"
alias anpls="sudo ansible-playbook"
alias anpl-user="ansible-playbook *user.yml"
alias anpl-sys="sudo ansible-playbook *sys.yml"
## Docker
alias dk="docker"
alias dkrmf="docker rm --force"
alias dkrmo="docker ps -a | grep 'weeks ago' | awk '{print $1}' | xargs --no-run-if-empty docker rm"
alias dk-spark='docker run --name pyspark -p 9000:8888 -v  "$(pwd)":/home/jovyan/work jupyter/pyspark-notebook'
alias dk-scipy="docker run --name pyscipy -p 9000:8888 -v "$(pwd)":/home/jovyan/work jupyter/scipy-notebook"
alias dk-fxmongo='docker run --name pymongo -p 9000:8888 -v "$(pwd)":/home/jovyan/work --link mongo:mongo freaxmind/nosql'
alias dk-mongo='docker run --name mongo -v "$(pwd)/data/db":/data/db mongo --smallfiles'
alias dk-zoo='docker run --name zookeeper --restart always zookeeper'
## Template
alias ck="cookiecutter"
## Project
alias m="make"
# Git
alias g="git"
alias gm="git submodule"
alias gn="$EDITOR .gitignore"
alias grc="$EDITOR ~/.gitconfig"
mygithub() { git clone git@github.com:fmind/$1.git }

# Alias: SHARING
alias httpserve="python3 -m http.server"

# Alias: EDITING
alias texmake="latexmk -pv"
alias texview="latexmk -pv"
alias texlive="latexmk -pvc"
alias texclean="latexmk -c"
alias texpurge="latexmk -C"
alias imgwhite="convert -flatten "
alias slides="git clone git@github.com:fmind/my-slides"

