"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'

[package]
disabled = true
